### ISSUE TITLE
[Task] research how images data is represented in Clearmash

### ISSUE THREAD

**Issue by OriHoch** [Beit-Hatfutsot/mojp-dbs-pipelines#25]
currently we use the /Documents/Get method in Clearmash to get all documents from a folder. 

The response from that API looks like [this](https://github.com/Beit-Hatfutsot/mojp-dbs-pipelines/blob/master/tests/mocks/clearmash-api-documents-get-115325-115353-115365-115371-115388-265694.json) - and I don't see any details about images

Ideally, we would like to have publicly accessible image url which we could use directly from our frontend.

So, how can we get images related to a web document?

**Comment by OriHoch** [comment]
related issue: #24

**Comment by omrisuissa** [comment]
Hi,
**Short answer:** you can get a public image URL (proxy and CDN safe) to present on your front end.

**Long answer:**
Photos are not part of the place entity type (template). We were asked to create a separate entity type named Photo to store the images data.
That means that on a Place document you will not get a list of images but a list of other documents that contains images.

You can see in your example that there is a file named “_c6_beit_hatfutsot_bh_base_template_multimedia_photos” – this field is a reference field to another document(s) containing the images of this document.

You can send an API request [GetDocumentsByRelationField](https://www.clearmash.com/skn/c7/Support/e4166/Web_Content_Management_Service) using [GetDocumentsByRelationFieldParameters](https://www.clearmash.com/skn/c7/Support/e4098/GetDocumentsByRelationFieldParameters) and get all the Photos documents that are related to this Place.
On the photos document, you will see properties named “FileEditor_PublicUrl” – this is the public URL :)

The structure is ‘~~ st ~~’ + ‘filename’. For example: ~~ st ~~067602786f3049609d613640b2c2087f.JPG
The ~~ st ~~ (without the spaces) is a placeholder for the media server URL, in your case https://bhfiles.clearmash.com/MediaServer/Images/.
You also need to ask for the size that you want (the media server will resize it, so you won’t download a large image for no reason). By adding it to the end of the file name 067602786f3049609d613640b2c2087f.JPG will become 067602786f3049609d613640b2c2087f**_100X100**.JPG
If you will ask for a size that is larger than the original image you will get the original image.
For caching reasons you will not get the exact the size you are asking but a proximity size (can be configured in the Storage Management admin page).

So let’s say that we want to get the images of the Place [184158](https://bh.clearmash.com/skn/c6/%D7%91%D7%99%D7%AA_%D7%94%D7%AA%D7%A4%D7%95%D7%A6%D7%95%D7%AA/e184158/%D7%A4%D7%A8%D7%99%D7%99%D7%91%D7%95%D7%A8) and we want every in 100X100 px. 
First we ask for the Photos documents using [GetDocumentsByRelationField](https://www.clearmash.com/skn/c7/Support/e4166/Web_Content_Management_Service) (entity id 184158, field “_c6_beit_hatfutsot_bh_base_template_multimedia_photos” ) . Then for each document, we will take the “FileEditor_PublicUrl”s. let’s say we have one image: ~~ st ~~067602786f3049609d613640b2c2087f.JPG so our final URL will be [**https://bhfiles.clearmash.com/MediaServer/Images/**067602786f3049609d613640b2c2087f**_100X100**.JPG](https://bhfiles.clearmash.com/MediaServer/Images/067602786f3049609d613640b2c2087f_100X100.JPG)
I know that Benny created a test that already does all this.

Best,
Omri

**Comment by OriHoch** [comment]
thanks @omrisuissa 

@Libisch will continue with the research and contact you if we have any questions

**Comment by Libisch** [comment]
@OriHoch @TheGrandVizier 

Photo URLs and all other related data for images of an item are located in a separate photo document. 
* Reference to these documents (as well as other related items), are available in `parsed_doc`, here:

```
'_c6_beit_hatfutsot_bh_base_template_multimedia_photos': ['RelatedDocuments', {'FirstPageOfReletedDocumentsIds': ['4d5e45cc663943698d6acc8d4cc0e3a8', '593aa14924d14f28baa966edc77c375c', 'e04076a3e78c4be18a1e31d0cc7119b6', '2d5533d9337b45238468d969fe47d963', 'ebf1c3851955457eab0ef14ae6f134e2', '6cc8310607e24058a982c919235be9e4', '9a1748725a454f9fa65b244b5ac9a48c', 'dfe9f984ba04472c97e1167cfdad4342', '22c759dfe1c94d0888d31ebcf4c41456', '6c86d96f39bc4d3eb09e6aa7ce1cf2ad', '9eecbf049e5e431cbab8445d5e429dc7', 'f3724ce76a6d47dc8613e3dfe4f9b1dd', '4026c28c04e94373b02410b95169c3fc'], 'FirstPageParams_ArchiveFilter': 2, 'FirstPageParams_ReverseOrder': False, 'Id': '_c6_beit_hatfutsot_bh_base_template_multimedia_photos', 'TotalItemsCount': 13}]
```
* Getting the docs: see instructions [above](https://github.com/Beit-Hatfutsot/mojp-dbs-pipelines/issues/25#issuecomment-310093396). The same can be applied to all related fields.

``` python
    def get_document_photos_docs(self, entity_id):
        return self._wcm_api_call("/Document/ByRelationField", {"EntityId": entity_id, "FieldId": "_c6_beit_hatfutsot_bh_base_template_multimedia_photos", "MaxNestingDepth": 1})
``` 
* In the response, all the relevant data including URLs is [here](https://gist.github.com/Libisch/ebe28d33237b9aab6a1e22f9bc76fa6c/c3cca310c252e63d3cfc996454435bde10aed0db#file-py-L85).

**Comment by OriHoch** [comment]
thanks @Libisch - you can open a PR for the changes to the Clearmash API

some questsions - 
* I see that in parsed doc the attribute is called FirstPageOfReletedDocumentsIds - does it mean that if there are too many images, we won't get all of them? Only the first page? how many items are in a page?
* Did you test this method for all document types in the same way?
* How do we get the main image? Is it just the first image in related documents? Is the main image marked somehow in the document?

**Comment by OriHoch** [comment]
I think it will be best to write some unit tests to go along with the PR of the changes to the Clearmash API

these unit tests can include mock data for each document type, will make it easier to test and also kept as reference for future development

**Comment by Libisch** [comment]
Replying @OriHoch [questions](https://github.com/Beit-Hatfutsot/mojp-dbs-pipelines/issues/25#issuecomment-313300286):
* (PR #50) In order to get related docs (including images), use `ClearmashApi.get_document_related_docs_by_fields(entity_id, field_id)`. This gets all related docs from all fields, and all docs from field, not only the ones specified in _"FirstPageOfReletedDocumentsIds"_.

* **TODO**: research _main_image_ (#23)

**Comment by omrisuissa** [comment]
@OriHoch  - FirstPageOfReletedDocumentsIds means this is the first page. to get more pages you need to use GetDocumentsByRelationField API

**Comment by OriHoch** [comment]
thanks @Libisch , looks like research is done, closing issue
