### ISSUE TITLE
[Task] Clearmash: research how to get standard geo data for places

### ISSUE THREAD

**Issue by Libisch** [Beit-Hatfutsot/mojp-dbs-pipelines#30]
Related issue: #16 
Items in places should have coordinates, instead they have a link to an embedded google map:
```
{'Id': '_c6_beit_hatfutsot_bh_place_google_maps',
      'Value': [{'ISO6391': 'en',
        'Value': '<p><iframe allowfullscreen="" frameborder="0" height="450" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3639100.5693534394!2d7.6804282320147825!3d50.96213621113465!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x479a721ec2b1be6b%3A0x75e85d6b8e91e55b!2sGermany!5e0!3m2!1sen!2sil!4v1498978137451" style="border:0" width="600"></iframe></p>\n'}]}],
    'Fields_LocalizedText': [{'Id': 'entity_name',
      'Value': [{'ISO6391': 'en', 'Value': 'GERMANY'},
       {'ISO6391': 'he', 'Value': 'גרמניה'}]},
```
Is a google map sufficient for our needs? 
Currently we use coordinates and apply them to an [openStreetMap](https://www.openstreetmap.org/#map=5/51.500/-0.100).

**Comment by OriHoch** [comment]
need to check how the data is represented on ClearMash CMS, if theoretically, as an end-user of the CMS, this data is available or not as coordinates

@TheGrandVizier @omrisuissa

**Comment by OriHoch** [comment]
it might be possible to parse the google map url and get the coordinates, but better not to go down that road

**Comment by OriHoch** [comment]
we will use the google map for now and embed it directly in the frontend
see Beit-Hatfutsot/dbs-back#208 and Beit-Hatfutsot/dbs-front#440
data is already available, no change is needed in pipelines

keeping this issue open because we might still need geo data in the future (probably for the large map with multiple results)

**Comment by OriHoch** [comment]
we will do geocoding to get geo data, will be handled in #16
