### ISSUE TITLE
Related photo documents should include a main_image field

### ISSUE THREAD

**Issue by Libisch** [Beit-Hatfutsot/mojp-dbs-pipelines#62]
Following issue: #51

Items should have a main image indication, but the field "_c6_beit_hatfutsot_bh_base_template_multimedia_photos" **is not found** in the clearmash API calls [get_document](https://gist.github.com/Libisch/0bdeb23c7e158070dd1bac8108278e96), or in it's related photos in [get_related_by_field](https://gist.github.com/Libisch/76734fd0c924335787ffbdbb5ff99fe9) (see examples for Einstein, Id 202567).

**Comment by Libisch** [comment]
@OriHoch

**Comment by OriHoch** [comment]
@Libisch I don't understand what's the expected output from this issue

is this a question for clearmash? or is it a development we need to do?

**Comment by Libisch** [comment]
@OriHoch  This was answered by Clearmash in #51 - but I can't find the relevant field ("bh_base_template_mg_items_main_image").

**Comment by OriHoch** [comment]
looks like you are right, but also in clearmash I don't see a main image for this item

so I guess, this item just doesn't have a main image

e.g.:
![image](https://user-images.githubusercontent.com/1198854/28562004-51c3260a-7129-11e7-9525-35804997fe9c.png)
![image](https://user-images.githubusercontent.com/1198854/28562030-6372d9ae-7129-11e7-8032-c69bdc0491de.png)

**Comment by OriHoch** [comment]
closing the issue as I don't see any more work needed for this
