### ISSUE TITLE
clearmash: should not sync items pending publish

### ISSUE THREAD

**Issue by OriHoch** [Beit-Hatfutsot/mojp-dbs-pipelines#75]
### reproduction
* have an item which is pending publication, e.g.: [link](https://bh.clearmash.com/skn/c6/%D7%91%D7%99%D7%AA_%D7%94%D7%AA%D7%A4%D7%95%D7%A6%D7%95%D7%AA/e200292/%D7%9E%D7%A1%D7%95%D7%A8%D7%91%D7%99_%D7%A2%D7%9C%D7%99%D7%99%D7%94_%D7%97%D7%95%D7%92%D7%92%D7%99%D7%9D_%D7%90%D7%AA_%D7%97%D7%92_%D7%94%D7%A4%D7%95%D7%A8%D7%99%D7%9D__%D7%9E%D7%95%D7%A1%D7%A7%D7%91%D7%94__%D7%91%D7%A8%D7%99%D7%94_%D7%9E__1978)
![image](https://user-images.githubusercontent.com/1198854/28874229-a235588a-7799-11e7-82fe-6c3a1e9a8ac2.png)
* look for that item in pipelines elasticsearch

#### expected
* should not be in elasticsearch

#### actual
* exists in elasticsearch
![image](https://user-images.githubusercontent.com/1198854/28874366-3b7e819c-779a-11e7-94dc-63af420e29ff.png)

### implementation notes
* the not allowed item has `'entity_has_pending_changes': True` - which other items don't

**Comment by omrisuissa** [comment]
An item can be both published and unpublished at the same time. The published state is related to a version and not of the item.
So this item should be in your search as long as you take that published version of this item.
If you wish not to get items that never been published, you should create a role and assign it to the API user.
The fact that the API user is an admin and can see unpublished items is not just a bug but also a very dangerous security risk.

**Comment by OriHoch** [comment]
thanks @omrisuissa - we will change the token

however, there is still something which doesn't make sense

see - 
![image](https://user-images.githubusercontent.com/1198854/28877816-30114bbc-77a6-11e7-927e-6abc7eec4db3.png)

there are 2 of the same item, with different clearmash numbers - one is published the other is not. Is this a normal thing in Clearmash when editing items?

**Comment by omrisuissa** [comment]
No, this is not the same item, this is a possible duplication from BHP (as you can see there is also a different BHP number).

**Comment by OriHoch** [comment]
that's what I suspected, cool, thanks

so the clearmash number will remain the same between edits?

**Comment by omrisuissa** [comment]
Yes

**Comment by OriHoch** [comment]
thanks

**Comment by OriHoch** [comment]
closing as the issue as it's related to this item not being allowed (the pending changes part is irelevant)
