### ISSUE TITLE
should ensure not allowed items are deleted from elasticsearch 

### ISSUE THREAD

**Issue by OriHoch** [Beit-Hatfutsot/mojp-dbs-pipelines#78]
looks like there is a bug with the process that deletes not allowed items

**Comment by OriHoch** [comment]
* initial sync -> all entities in DB -> allowed entities in ES
* unpublish item -> updated in DB to not allowed -> delete in ES
  * convert processor should add display_allowed column
  * 
* publish item -> updated in DB to allowed -> re-sync to ES
* delete item -> remains in DB -> remains in ES

**Comment by OriHoch** [comment]
merged and deployed, waiting for pipelines to run to see results

**Comment by OriHoch** [comment]
deployed successfully, the delete pipeline ran

**Comment by OriHoch** [comment]
moving back to in progress, I found a problem, will be fixed in #82

**Comment by OriHoch** [comment]
fixed + deployed + pipeline ran

**Comment by OriHoch** [comment]
closed means you tested it? could you write how you tested it? because I was having trouble testing it with live clearmash without some option to delete an entry in clearmash

**Comment by TheGrandVizier** [comment]
I used an assumption.
Given I know an item that is not "legit" for display, and I search it using general search,
Not finding that item would infer it is no longer in ES, correct?
