### ISSUE TITLE
Some items are listed as collection = unknown instead of their proper collection

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/mojp-dbs-pipelines#84]
Some items are defined as collection = unknown instead of the proper collection they should be a part of.

A good and current example is moscow.

**Reproduce:**
1. Go to General Search on test.dbs.bh.org.il
2. Search for Moscow

**Expected:**
Find moscow result under "Place" tab.

**Actual:**
Moscow is not listed in the results.

**Notes:**
Checked Clearmash, the item is valid for display.
[Here](https://devapi.dbs.bh.org.il:5601/app/kibana#/discover?_g=()&_a=(columns:!(title_en,title_he),filters:!((%27$$hashKey%27:%27object:1616%27,%27$state%27:(store:appState),meta:(alias:!n,disabled:!f,index:next-mojp-dev,key:collection,negate:!f,value:unknown),query:(match:(collection:(query:unknown,type:phrase))))),index:next-mojp-dev,interval:auto,query:(query_string:(analyze_wildcard:!t,query:moscow)),sort:!(_score,desc))) you can see that Moscow is assigned to collection = unknown

**Comment by OriHoch** [comment]
fixed in #72 - it's merged and deployed to dev
